## Path section
# Set $PATH if ~/.local/bin exist
if [ -d "$HOME/.local/bin" ]; then
    export PATH=$HOME/.local/bin:$PATH
fi

eval "$(starship init zsh)"
function set_win_title(){
    echo -ne "\033]0; $USER@$HOST:${PWD/$HOME/~} \007"
}
precmd_functions+=(set_win_title)


# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="${ZDOTDIR:-$ZSH}/custom"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(command-not-found git sudo z zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Advanced command-not-found hook
[[ -e /usr/share/doc/find-the-command/ftc.zsh ]] && source /usr/share/doc/find-the-command/ftc.zsh


[[ ! -f $ZDOTDIR/.aliasrc ]] || source $ZDOTDIR/.aliasrc

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
#[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# For WSL, share the same docker socket between different WSL distributions)
if [[ -f /mnt/wsl/shared-docker/docker.sock ]]; then  
  export DOCKER_SOCK="/mnt/wsl/shared-docker/docker.sock"
  export DOCKER_HOST="unix://$DOCKER_SOCK"
fi

# Load Mcfly
#export MCFLY_FUZZY=true
#export MCFLY_RESULTS=20
#export MCFLY_INTERFACE_VIEW=BOTTOM
#export MCFLY_RESULTS_SORT=LAST_RUN
#eval "$(mcfly init zsh)"

[[ ! -f $ZDOTDIR/.zshrc.local ]] || source $ZDOTDIR/.zshrc.local
